#NORMALİZATİON
x- min(x)/ Max(x)-Min(x) the values between 0-1 
and scikit learn use min max normalization 

#STANDARDİZATİON
X-mean/s.d

In [1]:
import pandas as pd

In [3]:
df= pd.read_csv('500hits.csv', encoding='latin-1')

In [5]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PLAYER  465 non-null    str
 1   YRS     465 non-null    int64
 2   G       465 non-null    int64
 3   AB      465 non-null    int64
 4   R       465 non-null    int64
 5   H       465 non-null    int64
 6   2B      465 non-null    int64
 7   3B      465 non-null    int64
 8   HR      465 non-null    int64
 9   RBI     465 non-null    int64
 10  BB      465 non-null    int64
 11  SO      465 non-null    int64
 12  SB      465 non-null    int64
 13  CS      465 non-null    int64
 14  BA      465 non-null    float64
 15  HOF     465 non-null    int64
dtypes: float64(1), int64(14), str(1)
memory usage: 63.7 KB

In [7]:
df=df.drop(columns=['PLAYER','CS'])

In [8]:
df.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,0.366,1
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,0.331,1
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,0.345,1
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,0.310,1
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,0.329,1

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YRS     465 non-null    int64
 1   G       465 non-null    int64
 2   AB      465 non-null    int64
 3   R       465 non-null    int64
 4   H       465 non-null    int64
 5   2B      465 non-null    int64
 6   3B      465 non-null    int64
 7   HR      465 non-null    int64
 8   RBI     465 non-null    int64
 9   BB      465 non-null    int64
 10  SO      465 non-null    int64
 11  SB      465 non-null    int64
 12  BA      465 non-null    float64
 13  HOF     465 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 51.0 KB

In [12]:
df.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,17.049,2048.699,7511.456,1150.314,2170.247,380.953,78.555,201.049,894.260,783.561,847.471,195.905,0.289,0.329
std,2.765,354.392,1294.066,289.635,424.191,96.483,49.363,143.623,486.193,327.432,489.224,181.846,0.021,0.475
min,11.000,1331.000,4981.000,601.000,1660.000,177.000,3.000,9.000,0.000,239.000,0.000,7.000,0.246,0.000
25%,15.000,1802.000,6523.000,936.000,1838.000,312.000,41.000,79.000,640.000,535.000,436.000,63.000,0.273,0.000
50%,17.000,1993.000,7241.000,1104.000,2076.000,366.000,67.000,178.000,968.000,736.000,825.000,137.000,0.287,0.000
75%,19.000,2247.000,8180.000,1296.000,2375.000,436.000,107.000,292.000,1206.000,955.000,1226.000,285.000,0.300,1.000
max,26.000,3308.000,12364.000,2295.000,4189.000,792.000,309.000,755.000,2297.000,2190.000,2597.000,1406.000,0.366,2.000

In [29]:
X1=df.iloc[:, 0:13] # Y DEĞİŞKENİ ALINMADI 
X1

     YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB     BA
0     24  3035  11434  2246  4189  724  295  117   726  1249   357  892  0.366
1     22  3026  10972  1949  3630  725  177  475  1951  1599   696   78  0.331
2     22  2789  10195  1882  3514  792  222  117   724  1381   220  432  0.345
3     20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358  0.310
4     21  2792  10430  1736  3430  640  252  101     0   963   327  722  0.329
..   ...   ...    ...   ...   ...  ...  ...  ...   ...   ...   ...  ...    ...
460   15  1920   6653  1105  1665  285   39  291   964  1224  1427  225  0.250
461   17  1829   6092   900  1664  379   10  275  1065   936  1453   20  0.273
462   15  1834   6499  1062  1661  338   67  210   761   960  1190  315  0.256
463   16  1822   6309   714  1660  254   25   54   593   396   489   74  0.263
464   15  1468   5629   785  1660  247   71   61   499   266   471  267  0.295

[465 rows x 13 columns]

In [30]:
X1.describe()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
count,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.00000,465.000000,465.000000,465.000000
mean,17.049462,2048.698925,7511.455914,1150.313978,2170.247312,380.952688,78.554839,201.049462,894.260215,783.56129,847.470968,195.905376,0.288712
std,2.765186,354.391805,1294.065992,289.635071,424.190773,96.483460,49.363030,143.622664,486.193456,327.43195,489.224289,181.845543,0.021208
min,11.000000,1331.000000,4981.000000,601.000000,1660.000000,177.000000,3.000000,9.000000,0.000000,239.00000,0.000000,7.000000,0.246000
25%,15.000000,1802.000000,6523.000000,936.000000,1838.000000,312.000000,41.000000,79.000000,640.000000,535.00000,436.000000,63.000000,0.273000
50%,17.000000,1993.000000,7241.000000,1104.000000,2076.000000,366.000000,67.000000,178.000000,968.000000,736.00000,825.000000,137.000000,0.287000
75%,19.000000,2247.000000,8180.000000,1296.000000,2375.000000,436.000000,107.000000,292.000000,1206.000000,955.00000,1226.000000,285.000000,0.300000
max,26.000000,3308.000000,12364.000000,2295.000000,4189.000000,792.000000,309.000000,755.000000,2297.000000,2190.00000,2597.000000,1406.000000,0.366000

In [31]:
X1.columns

Index(['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB',
       'BA'],
      dtype='str')

In [14]:
X2=df.iloc[:, 0:13]

In [16]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scale=StandardScaler() # direk x-mean/std yapıyor

In [32]:
X1=scale.fit_transform(X1)
X1=pd.DataFrame(X1, columns=['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB',
       'BA'])
X1

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
0,2.516295,2.786078,3.034442,3.787062,4.764193,3.559333,4.389485,-0.585841,-0.346449,1.423013,-1.003628,3.832067,3.648290
1,1.792237,2.760655,2.677044,2.760530,3.444971,3.569709,1.996457,1.909487,2.175837,2.493089,-0.309948,-0.649080,1.996159
2,1.792237,2.091184,2.075964,2.528955,3.171214,4.264876,2.909053,-0.585841,-0.350567,1.826585,-1.283965,1.299723,2.657012
3,1.068180,1.972543,2.849554,2.670665,3.055576,1.691719,-0.254611,0.410896,0.858071,0.912434,2.030966,0.892346,1.004881
4,1.430208,2.099658,2.257758,2.024329,2.972977,2.687780,3.517449,-0.697364,-1.841290,0.548609,-1.065016,2.896201,1.901752
...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,-0.741964,-0.363545,-0.664093,-0.156620,-1.192368,-0.995570,-0.802168,0.626972,0.143595,1.346579,1.185863,0.160169,-1.827343
461,-0.017907,-0.620600,-1.098077,-0.865170,-1.194728,-0.020260,-1.390285,0.515449,0.351555,0.466060,1.239066,-0.968376,-0.741657
462,-0.741964,-0.606476,-0.783226,-0.305243,-1.201808,-0.445661,-0.234331,0.062387,-0.274384,0.539436,0.700901,0.655627,-1.544120
463,-0.379936,-0.640373,-0.930208,-1.508049,-1.204168,-1.317215,-1.086086,-1.024962,-0.620298,-1.184914,-0.733523,-0.671101,-1.213694
464,-0.741964,-1.640344,-1.456250,-1.262649,-1.204168,-1.389844,-0.153211,-0.976171,-0.813845,-1.582371,-0.770355,0.391383,0.296825

In [35]:
X1.describe().round(2)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
count,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00
mean,-0.00,0.00,0.00,0.00,0.00,0.00,-0.00,-0.00,0.00,0.00,-0.00,0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-2.19,-2.03,-1.96,-1.90,-1.20,-2.12,-1.53,-1.34,-1.84,-1.66,-1.73,-1.04,-2.02
25%,-0.74,-0.70,-0.76,-0.74,-0.78,-0.72,-0.76,-0.85,-0.52,-0.76,-0.84,-0.73,-0.74
50%,-0.02,-0.16,-0.21,-0.16,-0.22,-0.16,-0.23,-0.16,0.15,-0.15,-0.05,-0.32,-0.08
75%,0.71,0.56,0.52,0.50,0.48,0.57,0.58,0.63,0.64,0.52,0.77,0.49,0.53
max,3.24,3.56,3.75,3.96,4.76,4.26,4.67,3.86,2.89,4.30,3.58,6.66,3.65

In [36]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
scalerMM= MinMaxScaler(feature_range= (0,1))

In [39]:
X2=scalerMM.fit_transform(X2)
X2=pd.DataFrame(X2, columns=['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB',
       'BA'])
X2

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
0,0.866667,0.861912,0.874035,0.971074,1.000000,0.889431,0.954248,0.144772,0.316064,0.517683,0.137466,0.632595,1.000000
1,0.733333,0.857360,0.811459,0.795750,0.778964,0.891057,0.568627,0.624665,0.849369,0.697078,0.268002,0.050751,0.708333
2,0.733333,0.737481,0.706217,0.756198,0.733096,1.000000,0.715686,0.144772,0.315194,0.585341,0.084713,0.303788,0.825000
3,0.600000,0.716237,0.841663,0.780401,0.713721,0.596748,0.205882,0.336461,0.570744,0.432086,0.708510,0.250893,0.533333
4,0.666667,0.738998,0.738047,0.670012,0.699881,0.752846,0.813725,0.123324,0.000000,0.371092,0.125915,0.511079,0.691667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,0.266667,0.297926,0.226466,0.297521,0.001977,0.175610,0.117647,0.378016,0.419678,0.504869,0.549480,0.155826,0.033333
461,0.400000,0.251897,0.150481,0.176505,0.001582,0.328455,0.022876,0.356568,0.463648,0.357253,0.559492,0.009292,0.225000
462,0.266667,0.254426,0.205607,0.272137,0.000395,0.261789,0.209150,0.269437,0.331302,0.369554,0.458221,0.220157,0.083333
463,0.333333,0.248356,0.179873,0.066706,0.000000,0.125203,0.071895,0.060322,0.258163,0.080472,0.188294,0.047891,0.141667
464,0.266667,0.069297,0.087769,0.108619,0.000000,0.113821,0.222222,0.069705,0.217240,0.013839,0.181363,0.185847,0.408333

In [40]:
X2.describe()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
count,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000
mean,0.403297,0.363024,0.342741,0.324270,0.201759,0.331630,0.246911,0.257439,0.389317,0.279119,0.326327,0.135029,0.355932
std,0.184346,0.179257,0.175276,0.170977,0.167731,0.156884,0.161317,0.192524,0.211665,0.167828,0.188381,0.129983,0.176730
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.266667,0.238240,0.208858,0.197757,0.070384,0.219512,0.124183,0.093834,0.278624,0.151717,0.167886,0.040029,0.225000
50%,0.400000,0.334851,0.306109,0.296930,0.164492,0.307317,0.209150,0.226542,0.421419,0.254741,0.317674,0.092924,0.341667
75%,0.533333,0.463328,0.433293,0.410272,0.282720,0.421138,0.339869,0.379357,0.525033,0.366991,0.472083,0.198713,0.450000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000